# Generated by Django 5.0.1 on 2025-12-20 09:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Country name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code', max_length=2, unique=True)),
                ('population', models.BigIntegerField(blank=True, help_text='Total population', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='users_count_code_d75ab4_idx'), models.Index(fields=['name'], name='users_count_name_fd8cc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='City name', max_length=100)),
                ('population', models.IntegerField(blank=True, help_text='City population', null=True)),
                ('founded_year', models.IntegerField(blank=True, help_text='Year city was founded', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2025)])),
                ('is_capital', models.BooleanField(default=False, help_text='Is this the capital?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(help_text='Country where city is located', on_delete=django.db.models.deletion.CASCADE, to='users.country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='User first name', max_length=100)),
                ('last_name', models.CharField(help_text='User last name', max_length=100)),
                ('email', models.EmailField(db_index=True, help_text='User email address', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20, null=True)),
                ('bio', models.TextField(blank=True, help_text='User biography')),
                ('is_active', models.BooleanField(default=True, help_text='Is user active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, help_text="User's city", null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'name'], name='users_city_country_f1282b_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_capital'], name='users_city_is_capi_1b8d9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['city'], name='users_user_city_id_5da16b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='users_user_created_5b2332_idx'),
        ),
    ]
